### ISSUE TITLE
remove Coffin

### ISSUE THREAD

**Issue by sebastian-philipp** [martin-bts/askbot-devel#13]
https://pypi.org/project/Coffin/

**Comment by martin-bts** [comment]
Coffin added a lot of things to Jinja2 to add things that are specific for Django templates. The native Django-Jinja2 integration leaves Jinja2 environments unchanged on purpose, as summarized [here on Stack Exchange](https://stackoverflow.com/a/44272431/1129682). The original source is claimed to be [the Django documentation](https://docs.djangoproject.com/en/1.11/topics/templates/#django.template.backends.jinja2.Jinja2)

We are a bit in between at the moment. For instance, our templates do contain {% load %} tags but (at least in Coffin >= 2.0) this tag is only a noop.

We cannot use the django.template.Library, because it is not meant to enrich Jinja2 environments. The library provided by django_jinja is.

**Comment by sebastian-philipp** [comment]
I have the impression that removing the coffin dependencies of askbot/templatetags/extra_filters_jinja.py is an achievable goal. The only thing needed is an inspiration of how to replace coffin there. (That's of course independent of the HTML templates.)
