### ISSUE TITLE
UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered

### ISSUE THREAD

**Issue by sebastian-philipp** [martin-bts/askbot-devel#7]
```
/home/sebastian/Repos/askbot-devel/.tox/py2.7/local/lib/python2.7/site-packages/askbot/views/api_v1.py:121: 
UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'django.contrib.auth.models.User'> QuerySet.
  paginator = Paginator(users, 10)
```

**Comment by martin-bts** [comment]
For reference: https://stackoverflow.com/questions/44033670/python-django-rest-framework-unorderedobjectlistwarning

Since we do not define `User`, but import it from Django, we must "find all of the `all`, `offset`, `filter`, and `limit `clauses and add a `order_by `clause to them." (from the linked SE post)

**Comment by RohanSingh07** [comment]
Please @martin-bts can you more clearly state how to add the order_by clause ?
